name: CI for Drupal

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone the code
        uses: actions/checkout@v1
      - name: Install DDEV
        uses: ddev/github-action-setup-ddev@v1
      - name: Set execute permission for Drush
        run: chmod +x /var/www/html/vendor/bin/drush
      - name: Build the website
        run: ddev build
      - name: Run YAML linter test
        run: yamllint .
