name: CI for Drupal

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone the code
        uses: actions/checkout@v1
      - name: Install DDEV
        uses: ddev/github-action-setup-ddev@v1

      - name: Build the website
        run: ddev build

      - name: Lint Modified YAML Files
        run: |
          FILES=$(git diff --name-only ${{ github.sha }} ${{ github.event.before }} | grep '\.yml$')
          if [ -n "$FILES" ]; then
            echo "Linting: $FILES"
            echo "$FILES" | xargs yamllint
          else
            echo "No YAML files to lint"
          fi

